### PR TITLE
Tidied up indentations of HTML code in Pristine-Zen-Garden.html

### PR DESCRIPTION
**Pull request by rahmona-henry**

### CODE REVIEW

**Comment by sureshnswamy** [comment]
Good work. 93 aside and 82,88 footer tags need not be indented. Dont forget to mention my name when you commit. cheers.

**Comment by sureshnswamy** [comment]
It all good. You can merge this branch.

**Comment by rahmona-henry** [comment]
Thanks Suresh:)

**Comment by rahmona-henry** [comment]
Suresh - just reading the assignment instructions I think you have to merge the branch - not me?

"Wait for a Github notification from them, review the pull request, and accept it if the indentation is perfect. Tidy their repo by deleting the tidying branch (They'll still have a copy locally if they need it)"

**Comment by sureshnswamy** [comment]
That is bit confusing. If you read the "wirte access" unless I am authorized by you I cannot delete anything in your repo. You have have to do it in this case. Can be clarified with coach.

**Pull request merged**
